name: Update README with Latest Release Downloads

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Get latest release version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/JoshMiles/alexandria/releases/latest | jq -r .tag_name)
          VERSION="${VERSION#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update README.md download links
        run: |
          python <<EOF
          import re
      
          readme = 'README.md'
          with open(readme, encoding='utf-8') as f:
              content = f.read()
      
          VERSION = "${{ steps.get_version.outputs.version }}"
          REPO = "JoshMiles/alexandria"
          MAC_M2_URL = f"https://github.com/{REPO}/releases/download/v{VERSION}/Alexandria-{VERSION}-arm64.dmg"
          MAC_URL = f"https://github.com/{REPO}/releases/download/v{VERSION}/Alexandria-{VERSION}.dmg"
          WIN_URL = f"https://github.com/{REPO}/releases/download/v{VERSION}/Alexandria-Setup-{VERSION}.exe"
          LINUX_URL = f"https://github.com/{REPO}/releases/download/v{VERSION}/Alexandria-{VERSION}.AppImage"
      
          # This regex matches the download table and replaces it entirely
          table_pattern = re.compile(
              r'(\| *Platform *\| *Download Link *\|[\r\n]+\|[-| ]+\|[\r\n]+)(\|.*\|.*\|[\r\n]+)*',
              re.IGNORECASE
          )
      
          new_table = (
              f"| **Windows** | [Alexandria-Setup-{VERSION}.exe]({WIN_URL}) |\n"
              f"| **macOS Silicon**   | [Alexandria-{VERSION}-arm64.dmg]({MAC_M2_URL}) |\n"
              f"| **macOS Intel**   | [Alexandria-{VERSION}-arm64.dmg]({MAC_URL}) |\n"
              f"| **Linux**   | [Alexandria-{VERSION}.AppImage]({LINUX_URL}) |\n"
          )
      
          if table_pattern.search(content):
              content = table_pattern.sub(r"\\1" + new_table, content)
          else:
              # If the table is missing, you can insert it below a specific heading if needed
              content = re.sub(
                  r'(## 🚀 Latest Release[\r\n]+)',
                  r"\\1" + new_table + "\n",
                  content,
                  count=1
              )
      
          with open(readme, 'w', encoding='utf-8') as f:
              f.write(content)
          EOF
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update README.md download links for release v${{ steps.get_version.outputs.version }}"
          file_pattern: README.md
          branch: main 
