name: Update README with Latest Release Downloads

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Extract version from release tag
        id: get_version
        run: |
          # Remove leading 'v' if present
          VERSION="${GITHUB_REF##*/}"
          VERSION="${VERSION#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update README.md download links
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          REPO="JoshMiles/alexandria"
          MAC_URL="https://github.com/$REPO/releases/download/v$VERSION/Alexandria-$VERSION-arm64.dmg"
          WIN_URL="https://github.com/$REPO/releases/download/v$VERSION/Alexandria-Setup-$VERSION.exe"
          LINUX_URL="https://github.com/$REPO/releases/download/v$VERSION/Alexandria-$VERSION.AppImage"
      
          echo "import re\\n\\nreadme = 'README.md'\\nwith open(readme, encoding='utf-8') as f:\\n    content = f.read()\\n\\ntable_pattern = re.compile(r'(\\| *Platform *\\| *Download Link *\\|[\\r\\n]+\\|[-| ]+\\|[\\r\\n]+)(\\|.*\\|.*\\|[\\r\\n]+){3}', re.IGNORECASE)\\n\\nnew_table = (\\n    '| Platform | Download Link |\\n'\\n    '|----------|--------------|\\n'\\n    f'| **Windows**  | [Alexandria-Setup-{VERSION}.exe]({WIN_URL}) |\\n'\\n    f'| **macOS**    | [Alexandria-{VERSION}-arm64.dmg]({MAC_URL}) |\\n'\\n    f'| **Linux**    | [Alexandria-{VERSION}.AppImage]({LINUX_URL}) |\\n'\\n)\\n\\nif table_pattern.search(content):\\n    content = table_pattern.sub(r\"\\\\1\" + new_table, content)\\nelse:\\n    content = re.sub(r'(## 🚀 Latest Release[\\r\\n]+)', r\"\\\\1\" + new_table + \"\\n\", content, count=1)\\n\\nwith open(readme, 'w', encoding='utf-8') as f:\\n    f.write(content)\\n" | python3

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update README.md download links for release v${{ steps.get_version.outputs.version }}"
          file_pattern: README.md
