name: Build and Release with Electron Forge

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: default
          - os: windows-latest
            arch: default
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build app (webpack)
        run: npm run build
      - name: Make distributables (macOS x64)
        if: matrix.os == 'macos-latest' && matrix.arch == 'x64'
        run: npm run make -- --arch=x64
      - name: Make distributables (macOS arm64)
        if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
        run: npm run make -- --arch=arm64
      - name: Make distributables (other)
        if: matrix.os != 'macos-latest'
        run: npm run make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.arch && matrix.arch || 'default' }}-artifacts
          path: out/
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: out/
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: out/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update README.md download links (Node.js)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
        run: node scripts/update-readme.js
      - name: Commit and push README.md changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update README.md download links for release ${GITHUB_REF}"
          file_pattern: README.md
          branch: main
