name: Build and Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build app (webpack)
        run: npm run build
      - name: Copy Electron main process and preload to dist
        run: cp ./main.js ./preload.js dist/
      - name: Get Electron version
        id: get_electron_version
        run: echo "version=$(node -p 'require(\"./package.json\").devDependencies.electron')" >> $GITHUB_OUTPUT
      - name: Create minimal Electron package.json in dist
        run: |
          cat > dist/package.json <<EOL
          {
            "name": "alexandria",
            "version": "0.1.11",
            "main": "main.js",
            "devDependencies": {
              "electron": "^${{ steps.get_electron_version.outputs.version }}"
            }
          }
          EOL
      - name: List dist contents
        run: ls -l dist/
      - name: Build Windows app
        uses: hydraulic-software/conveyor/actions/build@v18.1
        with:
          command: make windows-app
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          extra_flags: -Kapp.machines=win.x64 -f ci.conveyor.conf
      - name: Build Linux app
        uses: hydraulic-software/conveyor/actions/build@v18.1
        with:
          command: make linux-app
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          extra_flags: -Kapp.machines=linux.x64 -f ci.conveyor.conf
      - name: Build macOS Intel app
        uses: hydraulic-software/conveyor/actions/build@v18.1
        with:
          command: make mac-app
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          extra_flags: -Kapp.machines=mac.amd64 -f ci.conveyor.conf
      - name: Build macOS Apple Silicon app
        uses: hydraulic-software/conveyor/actions/build@v18.1
        with:
          command: make mac-app
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          extra_flags: -Kapp.machines=mac.aarch64 -f ci.conveyor.conf
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: out/
