name: Build and Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Install Conveyor
        run: npm install -g conveyor
      - name: Package app
        run: npm run build:conveyor
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: installers
          path: out/
      - name: Get release version
        id: get_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Update README download links
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: README.md
          write-mode: overwrite
          contents: |
            # Alexandria
            
            [![GitHub release](https://img.shields.io/github/v/release/JoshMiles/alexandria?include_prereleases&style=flat&label=latest%20release)](https://github.com/JoshMiles/alexandria/releases/latest)
            [![GitHub issues](https://img.shields.io/github/issues/JoshMiles/alexandria?style=flat)](https://github.com/JoshMiles/alexandria/issues)
            [![GitHub stars](https://img.shields.io/github/stars/JoshMiles/alexandria?style=flat)](https://github.com/JoshMiles/alexandria/stargazers)
            [![GitHub license](https://img.shields.io/github/license/JoshMiles/alexandria?style=flat)](https://github.com/JoshMiles/alexandria/blob/main/LICENSE)
            
            _Alexandria_ is a modern UI for searching Library Genesis (LibGen), featuring a built-in download manager and proxy support.
            
            ---
            
            ## 🚀 Latest Release
            
            Download the latest release for your platform:
            
            | Platform | Download Link |
            |----------|---------------|
            | **Windows** | [Alexandria-Setup-${{ steps.get_version.outputs.version }}.exe](https://github.com/JoshMiles/alexandria/releases/download/v${{ steps.get_version.outputs.version }}/Alexandria-Setup-${{ steps.get_version.outputs.version }}.exe) |
            | **macOS Silicon**   | [Alexandria-${{ steps.get_version.outputs.version }}-arm64.dmg](https://github.com/JoshMiles/alexandria/releases/download/v${{ steps.get_version.outputs.version }}/Alexandria-${{ steps.get_version.outputs.version }}-arm64.dmg) |
            | **macOS Intel**   | [Alexandria-${{ steps.get_version.outputs.version }}.dmg](https://github.com/JoshMiles/alexandria/releases/download/v${{ steps.get_version.outputs.version }}/Alexandria-${{ steps.get_version.outputs.version }}.dmg) |
            | **Linux**   | [Alexandria-${{ steps.get_version.outputs.version }}.AppImage](https://github.com/JoshMiles/alexandria/releases/download/v${{ steps.get_version.outputs.version }}/Alexandria-${{ steps.get_version.outputs.version }}.AppImage) |
            
            ---
            
            ## ✨ Features
            
            - **Modern UI** for searching and browsing LibGen
            - **DOI support** for finding sci-hub related articles
            - **Built-in Download Manager** for easy, reliable downloads
            - **Proxy Support** to help you access LibGen even if it's blocked in your region
            
            ---
            
            ## 🛠️ Getting Started
            
            Clone the repository:
            
            ```sh
            git clone https://github.com/JoshMiles/alexandria.git
            cd alexandria
            ```
            
            Install dependencies:
            
            ```sh
            npm install
            ```
            
            Build the project:
            
            ```sh
            npm run build
            ```
            
            Package the app for distribution (using [Hydraulic Conveyor](https://conveyor.hydraulic.dev/)):
            
            ```sh
            npm run build:conveyor
            ```
            
            This will generate installers for Windows, macOS, and Linux in the `out/` directory.
            
            ---
            
            ## 🔄 Auto-Updates
            
            Alexandria now uses [Hydraulic Conveyor](https://conveyor.hydraulic.dev/) for packaging and auto-updates. Updates are distributed via [GitHub Releases](https://github.com/JoshMiles/alexandria/releases). The app will automatically check for and download updates from the latest release.
            
            ---
            
            ## 🤝 Contributing
            
            Contributions are welcome! Please open issues or pull requests to help improve Alexandria.
            
            ---
            
            ## 📄 License
            
            This project is licensed under the MIT License. See the [LICENSE](https://github.com/JoshMiles/alexandria/blob/main/LICENSE) file for details.
            
            ---
            
            ## ⭐️ Community
            
            For more information, visit the [Alexandria GitHub repository](https://github.com/JoshMiles/alexandria).

      - name: Commit and push updated README
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest release links [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
